# Generated by Django 4.1.7 on 2023-04-02 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date1',
            field=models.DateField(default='2000-03-25'),
            preserve_default=False,
        ),
    ]
